### ISSUE TITLE
Can't see any Releases ...

### ISSUE THREAD

**Issue by vovoidvortex** [h1toru/ANXCameraT#6] opened 2023-10-31 04:34 UTC
Can't see any download-file in Github Release section.

**Comment by sorryusernameisalreadytaken** [comment] 2023-11-05 09:48
Duplicate of https://github.com/h1toru/ANXCameraT/issues/4

**Comment by h1toru** [comment] 2023-12-31 11:40
ANXCameraT has been released: https://github.com/h1toru/ANXCameraT/releases/tag/v3.0

**Closed by h1toru** 2023-12-31 11:40 UTC
Labels: duplicate
